[features]
seeds = false
[programs.localnet]
counter_program = "3eEKwf7z4eSKApGgGnH8Q6F8tpMn8JKYUMCNwtjbRAv9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ixmorrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
